# listen
ApiListen = "localhost:6065"

#batchUpload max num of keys once upload
MaxNum = 16

# enable golang pprof
PprofEnable = true

# pprof http addr
PprofListen = "localhost:6066"

[snowflake]
# zookeeper cluster addrs, multiple addrs split by ",".
ZkAddrs = [
    "localhost:2181"
]

# path
ZkPath = "/gosnowflake-servers"

# timeout
ZkTimeout = "15s"

# workid
WorkId = 1

[zookeeper]
# zookeeper cluster addrs, multiple addrs split by ",".
Addrs = [
    "localhost:2181"
]

# zookeeper heartbeat timeout.
Timeout = "15s"

# zookeeper storeroot path.
StoreRoot = "/rack"

# zookeeper volumeroot path
VolumeRoot = "/volume"

# zookeeper grouproot path
GroupRoot = "/group"

# zookeeper pullinterval
PullInterval = "10s"

[hbase]
master = ""
meta = ""
dialTimeout = "1s"
readTimeout = "10s"
readsTimeout = "10s"
writeTimeout = "10s"
writesTimeout = "10s"
    [hbase.zookeeperHbase]
    root = ""
    addrs = ["localhost:2181"]
    timeout = "30s"