PprofEnable = true

PprofListen = "localhost:2231"

HttpAddr = "localhost:2232"

BfsAddr = "localhost:2235"

Domain = "http://localhost:2232/"                                                                              

Prefix = "/bfs/"

MaxFileSize = 20971520

AliyunKeyId = "xxxxx"
AliyunKeySecret = "xxxxx"

NetUserName = "xxxx"
NetPasswd = "xxxx"

PurgeMaxSize = 100000

ExpireMc = "20m"

[limit]
rate = 150.0
Brust = 50

[mc]
name = "bfs"
proto = "tcp"
addr = "localhost:11213"
idle = 5
active = 10
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"

[Ats]
AtsServerList = [ "http://localhost:8080" ]


